### ISSUE TITLE
Question duplication nightmare begins anew

### ISSUE THREAD

**Issue by soubhikbarari** [soubhikbarari/svmkR#21]
Duplicated questions issue arising for survey number `407853711`.

**Comment by soubhikbarari** [comment]
Might be a back-end API issue. Going to now explicitly check for duplicate question data from the same respondent and only add the earliest one first.

**Comment by soubhikbarari** [comment]
@znpadgett , can you repull the survey using the dev branch version and check if the issue still persists?

**Comment by soubhikbarari** [comment]
Ah I may have accidentally had two versions of the function in there. Try again (from the dev branch) when you get a chance, making sure to restart R after re-installing!

**Comment by znpadgett** [comment]
looks good now!
