### ISSUE TITLE
Test out whether different themes work on uploading the survey

### ISSUE THREAD

**Issue by soubhikbarari** [soubhikbarari/svmkR#23]
`upload_qdoc` can take a `theme_id` parameter. It would be great if we could test out uploading the same survey using different theme IDs and seeing that this feature works. 

It would also be great to know what the theme number is for our usual research insights surveys (check out one of our recent research team surveys and then try looking at the [dev docs](https://developer.surveymonkey.com/api/v3/#api-endpoints-get-surveys) to see if theres a list of theme numbers or see if there's a theme number on the SurveyMonkey platform itself when creating a survey...).

If there is, it would be nice to have `theme_id` in `upload_qdoc` automatically set to that!

**Comment by jorgelsurveys** [comment]
[justine theme tests.R.zip](https://github.com/soubhikbarari/svmkR/files/11807822/justine.theme.tests.R.zip)

Different themes pose no issue! See lines 58 and 65.
